config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/users/:uid/add_song/:did/:title/:artist/:album', to: 'users#add_song'
  post '/users/:sid/remove_song/:uid', to: 'users#remove_song'
  post '/users/:uid/set_song/:did', to: 'users#set_song'

  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>About deej and the team</h1>
    <p>
      <h3>Project Description</h3>
      <p>Deej is a social media web application that allows users to interact, via commenting, following, and other features, with their friends and online DJs. Interactions include submitting suggestions to a media player queue, gaining thousands of followers and loyal fans, as well as simply listening to your best friend’s music as he listens to it.</p>

      <h3>Team Members</h3>
      <%= link_to image_tag("David_Scheibe.jpg", alt: "David's Pic", size: "90x90")%><br>
      David Scheibe<br>
      004124290<br>

      <%= link_to image_tag("Killian_Jackson.jpg", alt: "David's Pic", size: "90x90")%><br>
      Patrick Killian Jackson<br>
      504184347<br>

      <%= link_to image_tag("Nathaniel_Chu.jpg", alt: "David's Pic", size: "90x90")%><br>
      Nathaniel Chu<br>
      304449551<br>

      <%= link_to image_tag("Michael_Chen.jpg", alt: "David's Pic", size: "90x90")%><br>
      Michael Chen<br>
      904295193<br>
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to deej</h1>
  <% if logged_in? %>
    <section class="border">
        <%= button_to "View active DJ's", users_path, { :class => "buttonTo", :method => :get } %>
        <br>
        <%= button_to "Start sharing your own music!", current_user, { :class => "buttonTo", :method => :get } %>
    </section>
  <% else %>
  <h2>
    Please log in to begin listening to personalized DJ sets from all over!
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>